---
title: "resample"
author: "Kevin Glock"
date: "29 01 2021"
output:
  html_document:
    highlight: textmate
  toc_depth: 2
  number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
    echo = TRUE,
      include = TRUE,
    eval = TRUE,
  message = FALSE,
    results = 'hide',
      tidy = TRUE,
    tidy.opts = list(
      width.cutoff=60
      )
    )

#eval whether to evaluate the chunk
#echo whether to echo source code
#results 'markup', 'asis', 'hold', 'hide'
#tidy whether to reformat R code
#cache whether to cache results
#g.width, g.height, out.width, out.height device and output size of gures
#include whether to include the chunk results in output
#child lenames of child documents
#engine language name (R, python, . . . )
```


# resampling


Resample from the subset and check of plausibility.

```{r}
N <- 100000; SP <- sample(calc4$rowsum,
                          N, 
                          replace=T
                          ) # draw a sample of size N=100,000 from the aggregated rowsums

sd(SP) # 119385175
mean(SP) # 177189578
# 177189578-119385175=57804403
# 177189578+119385175=296574753

mean(calc4$rowsum) # 176699764
sd(calc4$rowsum) # 119066901
# 176699764-119066901=57632863
# 176699764+119066901=295766665

plot(density(SP),
     col ="grey",
     main = "Plausibilit채t",
     xlab= "Totalvariabilit채t T in Interview-Clustern (gepunktet MW +/- St.Abw.)",
     lwd=2); lines(density(calc4$rowsum), 
                   col= "black",
                   lwd=2); abline(v= c(57804403, 177189578, 296574753),
                                  col="grey",
                                  lty="dotted",
                                  lwd=3); abline(v= c(57632863, 176699764, 295766665),
                                  col="black",
                                  lty="dotted",
                                  lwd=3); legend("topright", legend = c("SP", "Resample"),  fill = c("black", "grey"), bty = "n");
                                    options(scipen=5) # plot the density of the original rowsums and the resampled ones


```


Get the densities

```{r}
dat2 <- data.frame(V1 = calc4$rowsum)
round(
  sort(
    with(dat2, V1/sum(V1))
    ), digits = 6)

round(
  cumsum(
    sort(
      with(dat2, V1/sum(V1))
      )
    ), digits = 6)

length(
  which(
    round(cumsum(sort(with(dat2, V1/sum(V1)))), digits = 6) < 0.05)
  ) # 46 interviewer are on the left side below the lower 5 percent
```


Get the interviewer id and rowsums ordered the same way like the densities.
Get the number of interviews.

```{r}
sort.calc4$INTNUM1
sort.calc4$rowsum


```


## resample for single interviews


```{r}
N2 <- 100000; SP2 <- sample(
                      calc6$rowsum,
                      N2,
                      replace=T
                      ) # now sample the same resample for the separated interviews

mean(SP2) # 21768691
sd(SP2) # 15497107
# 21768691-15497107=6271584
# 21768691+15497107=37265798

mean(calc6$rowsum) # 21812202
sd(calc6$rowsum) # 15601634
# 21812202-15601634=6210568
# 21812202+15601634=37413836



plot(density(SP2),
     col ="grey",
     main = "Plausibilit채t",
     xlab= "Totalvariabilit채t T in Einzelinterviews (gepunktet MW +/- St.Abw.)",
     lwd=2); lines(density(calc6$rowsum),
                   col= "black",
                   lwd=2); abline(v= c(6271584, 21768691, 37265798),
                                  col="grey",
                                  lty="dotted",
                                  lwd=3); abline(v= c(6210568, 21812202, 37413836),
                                  col="black",
                                  lty="dotted",
                                  lwd=3); legend("topright", legend = c("SP", "Resample"),  fill = c("black", "grey"), bty = "n");
                                    options(scipen=5)

dat3 <- data.frame(V1 = calc6$rowsum)

round(
  sort(
    with(dat3, V1/sum(V1))
    ), digits = 6)

round(
  cumsum(
    sort(with(dat3, V1/sum(V1)))
    ), digits = 6)

length(
  which(
    round(cumsum(sort(with(dat3, V1/sum(V1)))), digits = 6) < 0.05)
  ) # 281 interviews are on the left side below the lower 5 percent
```

